project:
  type: website

website:
  title: "Dollar42"
  description: "simplify dollars, live better"
  site-url: "https://www.dollar42.com"
  favicon: "favicon.png"
  draft-mode: unlinked
  open-graph: true
  google-analytics:
    tracking-id: "G-PZZF4E441G"
    storage: cookies
    anonymize-ip: true
    version: 4
  cookie-consent: false
  reader-mode: false
  search:
    location: navbar
    type: textbox
    keyboard-shortcut: "/"
  navbar:
    title: false
    logo: "logo.png"
    logo-alt: "Dollar42 logo"
    collapse: true
    collapse-below: "lg"
    background: dark
    search: true
    pinned: true
    left:
      - icon: house-fill
        href: index.qmd
        text: "Home"
      - icon: info-circle-fill
        text: "About"
        menu:
          - href: about.qmd
          - href: privacy.qmd
      - icon: file-spreadsheet-fill
        text: "The Spreadsheet"
        href: posts/millions-managed-with-a-google-sheet
    right:
      - icon: envelope-at-fill
        href: subscribe.qmd
      - icon: rss
        href: index.xml
  margin-header:
    - margin_subscribe.html
  margin-footer:
    - |
      <p class="mt-5 mb-0"><small>Copyright &copy; Dollar 42, LLC</small></p>
      <p><small><a class="text-decoration-none" href="/about.html"><i class="bi bi-info-circle-fill"></i> about/disclaimer</a></small></p>
format:
  html:
    anchor-sections: true
    email-obfuscation: references
    link-external-icon: true
    link-external-newwindow: true
    theme:
      - sandstone
      - brand
      - custom.scss
    include-in-header:
      - text: |-
          <script type="text/javascript">
          function submitAsUsual(e) {
            e.target.closest("form").submit();
          }
          </script>
      - text: |-
          <meta name="twitter:card" content="summary_large_image">
          <meta name="twitter:creator" content="@alindeman">
