project:
  type: website

website:
  title: "dollar42"
  navbar:
    search: true
    right:
      - about.qmd
      - text: "Meet"
        href: https://cal.com/dollar42/consultation

format:
  html:
    theme:
      - sandstone
      - brand
    css: styles.css
