project:
  type: website

website:
  title: "Dollar42"
  description: "simplify $, live better"
  site-url: "https://www.dollar42.com"
  google-analytics:
    tracking-id: "G-XK79WBDEMB"
    storage: cookies
    anonymize-ip: true
    version: 4
  cookie-consent: true
  reader-mode: true
  search:
    location: navbar
    type: textbox
    keyboard-shortcut: "/"
  navbar:
    background: primary
    search: true
    pinned: true
    left:
      - about.qmd
      - text: "Meet"
        menu:
          - text: "Intro"
            href: https://cal.com/dollar42/intro
          - text: "Consultation (paid)"
            href: https://cal.com/dollar42/consultation

format:
  html:
    theme:
      - sandstone
      - brand
      - custom.scss
