project:
  type: website

website:
  title: "Dollar42"
  description: "simplify finances, live better"
  site-url: "https://www.dollar42.com"
  google-analytics:
    tracking-id: "G-XK79WBDEMB"
    storage: cookies
    anonymize-ip: true
    version: 4
  cookie-consent:
    type: implied
    style: simple
    site-name: "Dollar42"
    policy-url: "https://www.dollar42.com/privacy.html" # TODO
  reader-mode: true
  search:
    location: navbar
    type: textbox
    keyboard-shortcut: "/"
  navbar:
    title: false
    logo: "logo.png"
    logo-alt: "Dollar42 logo"
    collapse: true
    collapse-below: "lg"
    background: dark
    search: true
    pinned: true
    left:
      - icon: house-fill
        href: index.qmd
        text: "Home"
      - icon: info-circle-fill
        text: "About"
        menu:
          - href: about.qmd
          - href: privacy.qmd
format:
  html:
    theme:
      - sandstone
      - brand
      - custom.scss
