project:
  type: website

website:
  title: "Dollar42"
  description: "simplify dollars, live better"
  site-url: "https://www.dollar42.com"
  favicon: "favicon.png"
  google-analytics:
    tracking-id: "G-PZZF4E441G"
    storage: cookies
    anonymize-ip: true
    version: 4
  cookie-consent:
    type: implied
    style: simple
    site-name: "Dollar42"
    policy-url: "https://www.dollar42.com/privacy.html"
  reader-mode: true
  search:
    location: navbar
    type: textbox
    keyboard-shortcut: "/"
  navbar:
    title: false
    logo: "logo.png"
    logo-alt: "Dollar42 logo"
    collapse: true
    collapse-below: "lg"
    background: dark
    search: true
    pinned: true
    left:
      - icon: house-fill
        href: index.qmd
        text: "Home"
      - icon: info-circle-fill
        text: "About"
        menu:
          - href: about.qmd
          - href: privacy.qmd
  margin-header: |-
    <div class="ml-embedded" data-form="k2N5Mp"></div>
  margin-footer: |-
    <p class="mt-5 mb-0"><small>Copyright &copy; Dollar 42, LLC</small></p>
    <p><small><a href="/about.html"><i class="bi bi-info-circle-fill"></i> about/disclaimer</a></small></p>
format:
  html:
    include-in-header:
      - text: |-
          <!-- MailerLite Universal -->
          <script>
              (function(w,d,e,u,f,l,n){w[f]=w[f]||function(){(w[f].q=w[f].q||[])
              .push(arguments);},l=d.createElement(e),l.async=1,l.src=u,
              n=d.getElementsByTagName(e)[0],n.parentNode.insertBefore(l,n);})
              (window,document,'script','https://assets.mailerlite.com/js/universal.js','ml');
              ml('account', '1412225');
          </script>
          <!-- End MailerLite Universal -->
    theme:
      - sandstone
      - brand
      - custom.scss
