project:
  type: website

website:
  title: "dollar42"
  site-url: "https://www.dollar42.com"
  description: "simplify $, live well"
  search:
    location: navbar
    type: textbox
    keyboard-shortcut: "/"
  navbar:
    background: primary
    search: true
    pinned: true
    left:
      - about.qmd
      - text: "Meet"
        menu:
          - text: "Intro"
            href: https://cal.com/dollar42/intro
          - text: "Consultation (paid)"
            href: https://cal.com/dollar42/consultation

format:
  html:
    theme:
      - sandstone
      - brand
      - custom.scss
