project:
  type: website

website:
  title: "dollar42"
  description: "simplify $, live well"
  navbar:
    background: primary
    search: true
    pinned: true
    left:
      - about.qmd
      - text: "Meet"
        href: https://cal.com/dollar42/consultation

format:
  html:
    theme:
      - sandstone
      - brand
    css: styles.css
