---
title: Privacy Policy
---

Dollar 42, LLC ("Company", "we," or "us") respects your privacy and is committed to protecting it through this Privacy Policy.

This Privacy Policy governs your access to and use of dollar42.com, including any content, functionality and services offered on or through dollar42.com (the "Website"), whether as a guest or a registered user.

When accessing the Website, we will learn certain information about you, both automatically and through voluntary actions you may take, during your visit. This policy applies to information we collect on the Website and in email, text or other electronic messages between you and the Website.

Please read the Privacy Policy carefully before you start to use the Website. By using the Website, you accept and agree to be bound and abide by the Privacy Policy. If you do not want to agree to the Privacy Policy, you must not access or use the Website.

## Children Under The Age Of 13

The Website is not intended for children under 13 years of age. No one under age 13 may provide any information to or on the Website. We do not knowingly collect personal information from children under 13. If you are under 13, do not use or provide any information on this Website or on or through any of its features/register on the Website, make any purchases through the Website, use any of the interactive or public comment features of this Website or provide any information about yourself to us, including your name, address, telephone number, email address, or any screen name or user name you may use.

If we learn we have collected or received personal information from a child under 13 without verification of parental consent, we will delete that information. If you believe we might have any information from or about a child under 13, please contact us at privacy@dollar42.com.

## Information We Collect About You

When you access the Website, the Comapny will learn certain information about you during your visit.

### Information You Provide To Us

The Website provides various places for users to provide information. We collect information that users provide by filling out forms on the Website, communicating with us via contact forms, responding to surveys, search queries on the search feature, providing comments or other feedback, and providing information when ordering a product or service via the Website.

We use information you provide to us to deliver the requested product and/or service, to improve the overall performance, and to provide you with offers, promotions, and information.

### Information We Collect Through Automatic Data Collection Technology

As you navigate through the Website, we may use automatic data collection technologies including, but not limited to, Google Analytics and Google Tag Manager to collect certain information about your equipment, browsing actions, and patterns. This will generally include information about your location, your traffic pattern through the Website, and any communications between your computer and the Website. Among other things, we will collect data about the type of computer you use, your Internet connection, your IP address, your operating system, and your browser type.

## Use of Cookies and Pixels

Similar to other commercial websites, the Website utilizes standard technologies called "cookies" and server logs to collect information about how the Website is used. Information gathered through cookies and server logs may include the date and time of visits, the pages viewed, time spent at our site, and the websites visited just before and just after our own, as well as your IP address.

A cookie is a small text document, which often includes an anonymous unique identifier. When you visit a website, that site's computer asks your computer for permission to store this file in a part of your hard drive specifically designated for cookies. Each website can send its own cookie to your browser if your browser's preferences allow it, but (to protect your privacy) your browser only permits a website to access the cookies it has already sent to you, not the cookies sent to you by other sites.

We reserve the right to use technological equivalents of cookies, including social media pixels. These pixels allow social media sites to track visitors to outside websites so as to tailor advertising messages users see while visiting that social media website. We reserve the right to use these pixels in compliance with the policies of the various social media sites.

## Third Party Use of Cookies

Some content or applications, including advertisements, on the Website are served by third-parties, including advertisers, ad networks and servers, content providers, and application providers. These third parties may use cookies alone or in conjunction with web beacons or other tracking technologies to collect information about you when you use the Website. The information they collect may be associated with your personal information or they may collect information, including personal information, about your online activities over time and across different websites and other online services. They may use this information to provide you with interest-based (behavioral) advertising or other targeted content.

We do not control these third parties' tracking technologies or how they may be used. If you have any questions about an advertisement or other targeted content, you should contact the responsible provider directly.

## Email Information

If you choose to correspond with us through email, we may retain the content of your email messages together with your email address and our responses. We provide the same protections for these electronic communications that we employ in the maintenance of information received online, mail, and telephone. This also applies when you register for the Website, sign up through any of our forms using your email address or make a purchase on this site. For further information see the email policies below.

## Email Policies

The Company is committed to keeping your email address confidential. We do not sell, rent, or lease our email subscription lists to third parties, and will not disclose your email address to any third parties except as allowed in the section titled Disclosure of Your Information.

We will maintain the information you send via email in accordance with applicable law.

Our newsletter or promotional emails provide users the opportunity to opt-out of receiving communications from us and our partners by reading the unsubscribe instructions located at the bottom of any newsletter or promotional email they receive from us.

## How And Why We Collect Information

The Company collects your information in order to record and support your participation in the activities you select. If you register to download a book or resources, sign up for a newsletter, and/or purchase a product from us, we collect your information. We use this information to track your preferences and to keep you informed about the products and services you have selected to receive and any related products and/or services. As a visitor to the Website, you can engage in most activities without providing any personal information. It is only when you seek to download resources and/or register for services that you are required to provide information.

If you are outside the European Union and opt to receive any free resources, participate in any free training programs, register for a webinar, register for a live event, register for a seminar, or purchase any products sold by the Company, we will automatically enroll you to receive our free email newsletter. If you do not wish to receive this newsletter, you can unsubscribe anytime. We include an "unsubscribe" link at the bottom of every newsletter or promotional we send. If you ever have trouble unsubscribing, you can send an email to privacy@dollar42.com requesting to unsubscribe from future emails.

If you are in the European Union and opt to receive any free resources, participate in any free training programs, register for a webinar, register for a live event, register for a seminar, or purchase any products sold by the Company, we will only enroll you to receive our free email newsletter if you affirmatively consent to it. If you do not wish to receive this newsletter, you can unsubscribe anytime. We include an "unsubscribe" link at the bottom of every newsletter or promotional email we send. If you ever have trouble unsubscribing, you can send an email to privacy@dollar42.com requesting to unsubscribe from future emails.

## How Do We Use the Information That You Provide to Us?

The Company uses personal information for purposes of presenting our Website and its contents to you, providing you with information, providing you with offers for products and services, providing you with information about your subscriptions and products, carrying out any contract between you and the Company, administering our business activities, providing customer service, and making available other items and services to our customers and prospective customers.

From time-to-time, we may use the information you provide to us to make you offers to purchase products and services provided by third parties in exchange for a commission to be paid to us by such third parties. Should you opt to take part in such promotions, the third parties will receive your information.

From time-to-time, we may use the information you provide to us to display advertisements to you that are tailored to your personal characteristics, interests, and activities.

## Disclosure Of Your Information

As a general rule, the Company does not sell, rent, lease or otherwise transfer any information collected whether automatically or through your voluntary action.

We may disclose your personal information to our subsidiaries, affiliates and service providers for the purpose of providing our services to you.

We may disclose your personal information to a third party, including a lawyer or collection agency, when necessary to enforce our terms of service or any other agreement between you and the Company.

We may provide your information to any successor in interest in the event of a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of the Company's assets and/or business.

We may disclose information when legally compelled to do so. We may disclosure information when we, in good faith, believe that the law requires it or for the protection of our legal rights or when compelled by a court or other governmental entity to do so.

## How Do We Protect Your Information and Secure Information Transmissions?

The Company employs commercially reasonable methods to ensure the security of the information you provide to us and the information we collect automatically. This includes using standard security protocols and working only with reputable third-party vendors.

Email is not recognized as a secure medium of communication. For this reason, we request that you do not send private information to us by email.

The Company may use software programs to create summary statistics, which are used for such purposes as assessing the number of visitors to the different sections of our site, what information is of most and least interest, determining technical design specifications, and identifying system performance or problem areas.

For site security purposes and to ensure that this service remains available to all users, the Company uses software programs to monitor network traffic to identify unauthorized attempts to upload or change information, or otherwise cause damage.

## Policy Changes

It is our policy to post any changes we make to our privacy policy on this page. You are responsible for periodically visiting the Website and this Privacy Policy to check for any changes.

## Visitors' GDPR Rights

If you are within the European Union, you are entitled to certain information and have certain rights under the General Data Protection Regulation. Those rights include:

We will retain the any information you choose to provide to us until the earlier of: (a) you asking us to delete the information, (b) our decision to cease using our existing data providers, or (c) the Company decides that the value in retaining the data is outweighed by the costs of retaining it.

You have the right to request access to your data that the Company stores and the rights to either rectify or erase your personal data.

You have the right to seek restrictions on the processing of your data.

You have the right to object to the processing of your data and the right to the portability of your data.

To the extent that you provided consent to the Company's processing of your personal data, you have the right to withdraw that consent at any time, without affecting the lawfulness of processing based upon consent that occurred prior to your withdrawal of consent.

You have the right to lodge a complaint with a supervisory authority that has jurisdiction over issues related to the General Data Protection Regulation.

We require only the information that is reasonably required to enter into a contract with you. We will not require you to provide consent for any unnecessary processing as a condition of entering into a contract with us.

## Contact Us

Email: privacy@dollar42.com
